//! Generates Rust code for dofus-protocol from extracted protocol classes.

use crate::extractor::{FieldType, ProtocolClass, ProtocolEnum, TypeHierarchy};
use std::collections::{HashMap, HashSet};
use std::fmt::Write;
use std::path::Path;

pub fn generate(
    classes: &[ProtocolClass],
    enums: &[ProtocolEnum],
    hierarchies: &[TypeHierarchy],
    output_dir: &Path,
) -> anyhow::Result<()> {
    std::fs::create_dir_all(output_dir)?;

    // Build hierarchy lookup: base_name → TypeHierarchy
    let hierarchy_map: HashMap<String, &TypeHierarchy> = hierarchies
        .iter()
        .map(|h| (h.base_name.clone(), h))
        .collect();

    // Collect all TypeManager base names referenced by any field
    let mut all_tm_refs: HashSet<String> = HashSet::new();
    for cls in classes {
        for f in &cls.fields {
            collect_type_manager_refs(&f.field_type, &mut all_tm_refs);
        }
    }

    // Extend hierarchies with trivial entries for any referenced but missing bases
    let existing_bases: HashSet<String> = hierarchies.iter().map(|h| h.base_name.clone()).collect();
    let mut all_hierarchies: Vec<TypeHierarchy> = hierarchies.to_vec();
    let id_map: HashMap<String, u32> = classes.iter()
        .filter(|c| !c.is_message)
        .map(|c| (c.name.clone(), c.protocol_id))
        .collect();

    for name in &all_tm_refs {
        if !existing_bases.contains(name) && !name.is_empty() {
            if let Some(&id) = id_map.get(name) {
                all_hierarchies.push(TypeHierarchy {
                    base_name: name.clone(),
                    variants: vec![(name.clone(), id)],
                });
            }
        }
    }

    let poly_bases: HashSet<String> = all_hierarchies.iter().map(|h| h.base_name.clone()).collect();

    let messages: Vec<&ProtocolClass> = classes.iter().filter(|c| c.is_message).collect();
    let types: Vec<&ProtocolClass> = classes.iter().filter(|c| !c.is_message).collect();

    let mut message_groups: HashMap<String, Vec<&ProtocolClass>> = HashMap::new();
    for msg in &messages {
        let domain = infer_domain(&msg.full_name);
        message_groups.entry(domain).or_default().push(msg);
    }

    let types_dir = output_dir.join("types");
    std::fs::create_dir_all(&types_dir)?;
    generate_types(&types, &types_dir, &poly_bases)?;

    // Generate polymorphic variant enums in types dir
    generate_variant_enums(&all_hierarchies, &types_dir)?;

    let messages_dir = output_dir.join("messages");
    std::fs::create_dir_all(&messages_dir)?;
    generate_messages(&message_groups, &messages_dir, &poly_bases)?;

    // Generate enums
    let enums_dir = output_dir.join("enums");
    std::fs::create_dir_all(&enums_dir)?;
    generate_enums(enums, &enums_dir)?;

    generate_registry(classes, output_dir)?;
    generate_mod_rs(output_dir, &message_groups)?;

    tracing::info!(
        messages = messages.len(),
        types = types.len(),
        enums = enums.len(),
        hierarchies = hierarchies.len(),
        groups = message_groups.len(),
        "Code generation complete"
    );

    Ok(())
}

fn infer_domain(full_name: &str) -> String {
    let parts: Vec<&str> = full_name.split('.').collect();
    if let Some(idx) = parts.iter().position(|&p| p == "messages") {
        let domain_parts: Vec<&str> = parts[idx + 1..]
            .iter()
            .take_while(|&&p| p.chars().next().map(|c| c.is_lowercase()).unwrap_or(false))
            .copied()
            .collect();
        if !domain_parts.is_empty() {
            return domain_parts.join("_");
        }
    }
    "other".to_string()
}

// ─── Types ───────────────────────────────────────────────────────

fn generate_types(types: &[&ProtocolClass], dir: &Path, poly_bases: &HashSet<String>) -> anyhow::Result<()> {
    let mut mod_rs = String::new();
    writeln!(mod_rs, "// Auto-generated by protocol-gen — do not edit\n")?;

    for typ in types {
        let file_name = to_snake_case(&typ.name);
        let file_path = dir.join(format!("{file_name}.rs"));
        let code = generate_file_for_class(typ);
        std::fs::write(&file_path, &code)?;

        writeln!(mod_rs, "mod {file_name};")?;
        writeln!(mod_rs, "pub use {file_name}::{};", typ.name)?;
    }

    std::fs::write(dir.join("mod.rs"), &mod_rs)?;
    Ok(())
}

// ─── Messages ────────────────────────────────────────────────────

fn generate_messages(
    groups: &HashMap<String, Vec<&ProtocolClass>>,
    dir: &Path,
    poly_bases: &HashSet<String>,
) -> anyhow::Result<()> {
    let mut mod_rs = String::new();
    writeln!(mod_rs, "// Auto-generated by protocol-gen — do not edit\n")?;

    let mut sorted_groups: Vec<_> = groups.keys().collect();
    sorted_groups.sort();

    for group in sorted_groups {
        let msgs = &groups[group];
        let file_path = dir.join(format!("{group}.rs"));
        let mut code = String::new();
        writeln!(code, "// Auto-generated by protocol-gen — do not edit")?;
        writeln!(code, "#![allow(unused_imports, dead_code)]\n")?;
        writeln!(code, "use dofus_io::{{BigEndianReader, BigEndianWriter, DofusDeserialize, DofusMessage, DofusSerialize}};")?;
        writeln!(code, "use dofus_io::boolean_byte_wrapper;")?;
        writeln!(code, "use super::super::types::*;")?;
        writeln!(code, "use anyhow::Result;\n")?;

        for msg in msgs {
            writeln!(code, "{}", generate_struct(msg, true))?;
        }

        std::fs::write(&file_path, &code)?;
        writeln!(mod_rs, "pub mod {group};")?;
    }

    std::fs::write(dir.join("mod.rs"), &mod_rs)?;
    Ok(())
}

// ─── Struct generation ───────────────────────────────────────────

fn generate_file_for_class(cls: &ProtocolClass) -> String {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by protocol-gen — do not edit").unwrap();
    writeln!(out, "#![allow(unused_imports, dead_code)]\n").unwrap();
    if cls.is_message {
        writeln!(out, "use dofus_io::{{BigEndianReader, BigEndianWriter, DofusDeserialize, DofusMessage, DofusSerialize}};").unwrap();
    } else {
        writeln!(out, "use dofus_io::{{BigEndianReader, BigEndianWriter, DofusDeserialize, DofusSerialize, DofusType}};").unwrap();
    }
    writeln!(out, "use dofus_io::boolean_byte_wrapper;").unwrap();
    writeln!(out, "use super::*;").unwrap();
    writeln!(out, "use anyhow::Result;\n").unwrap();
    writeln!(out, "{}", generate_struct(cls, false)).unwrap();
    out
}

fn generate_struct(cls: &ProtocolClass, _in_group_file: bool) -> String {
    let mut out = String::new();

    // Collect consecutive booleans that use BooleanByteWrapper
    let bool_groups = collect_boolean_groups(&cls.fields);

    writeln!(out, "/// Protocol {} — ID: {}", if cls.is_message { "message" } else { "type" }, cls.protocol_id).unwrap();
    writeln!(out, "#[derive(Debug, Clone, Default)]").unwrap();
    writeln!(out, "pub struct {} {{", cls.name).unwrap();
    for field in &cls.fields {
        let rust_type = field_type_to_rust(&field.field_type);
        writeln!(out, "    pub {}: {},", sanitize_field_name(&field.name), rust_type).unwrap();
    }
    writeln!(out, "}}\n").unwrap();

    // Serialize
    writeln!(out, "impl DofusSerialize for {} {{", cls.name).unwrap();
    writeln!(out, "    fn serialize(&self, writer: &mut BigEndianWriter) {{").unwrap();
    write_serialize_body(&mut out, &cls.fields, &bool_groups);
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();

    // Deserialize
    writeln!(out, "impl DofusDeserialize for {} {{", cls.name).unwrap();
    writeln!(out, "    fn deserialize(reader: &mut BigEndianReader) -> Result<Self> {{").unwrap();
    write_deserialize_body(&mut out, &cls.fields, &bool_groups);
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();

    // Trait impl
    if cls.is_message {
        writeln!(out, "impl DofusMessage for {} {{", cls.name).unwrap();
        writeln!(out, "    const MESSAGE_ID: u16 = {};", cls.protocol_id).unwrap();
        writeln!(out, "}}").unwrap();
    } else {
        writeln!(out, "impl DofusType for {} {{", cls.name).unwrap();
        writeln!(out, "    const TYPE_ID: u16 = {};", cls.protocol_id).unwrap();
        writeln!(out, "}}").unwrap();
    }

    out
}

// ─── Boolean groups ──────────────────────────────────────────────

/// Find groups of consecutive Bool fields that use BooleanByteWrapper.
/// Returns a map: first_field_index → list of field indices in the group.
fn collect_boolean_groups(fields: &[crate::extractor::ProtocolField]) -> HashMap<usize, Vec<usize>> {
    let mut groups: HashMap<usize, Vec<usize>> = HashMap::new();
    let mut i = 0;
    while i < fields.len() {
        if fields[i].write_method == "BooleanByteWrapper" {
            let start = i;
            let mut group = vec![i];
            i += 1;
            while i < fields.len() && fields[i].write_method == "BooleanByteWrapper" {
                group.push(i);
                i += 1;
            }
            groups.insert(start, group);
        } else {
            i += 1;
        }
    }
    groups
}

// ─── Serialize body ──────────────────────────────────────────────

fn write_serialize_body(
    out: &mut String,
    fields: &[crate::extractor::ProtocolField],
    bool_groups: &HashMap<usize, Vec<usize>>,
) {
    let mut i = 0;
    while i < fields.len() {
        let field = &fields[i];
        let fname = sanitize_field_name(&field.name);

        // Boolean group?
        if let Some(group) = bool_groups.get(&i) {
            writeln!(out, "        let mut _flag: u8 = 0;").unwrap();
            for (bit, &fi) in group.iter().enumerate() {
                let gname = sanitize_field_name(&fields[fi].name);
                writeln!(out, "        _flag = boolean_byte_wrapper::set_flag(_flag, {bit}, self.{gname}).unwrap();").unwrap();
            }
            writeln!(out, "        writer.write_byte(_flag);").unwrap();
            i += group.len();
            continue;
        }

        // Skip if this field is part of a boolean group (not the first)
        if field.write_method == "BooleanByteWrapper" {
            i += 1;
            continue;
        }

        match &field.field_type {
            FieldType::Bool => writeln!(out, "        writer.write_boolean(self.{fname});").unwrap(),
            FieldType::Byte => writeln!(out, "        writer.write_byte(self.{fname});").unwrap(),
            FieldType::UByte => writeln!(out, "        writer.write_byte(self.{fname});").unwrap(),
            FieldType::Short => writeln!(out, "        writer.write_short(self.{fname});").unwrap(),
            FieldType::UShort => writeln!(out, "        writer.write_ushort(self.{fname});").unwrap(),
            FieldType::Int => writeln!(out, "        writer.write_int(self.{fname});").unwrap(),
            FieldType::UInt => writeln!(out, "        writer.write_uint(self.{fname});").unwrap(),
            FieldType::Float => writeln!(out, "        writer.write_float(self.{fname});").unwrap(),
            FieldType::Double => writeln!(out, "        writer.write_double(self.{fname});").unwrap(),
            FieldType::String => writeln!(out, "        writer.write_utf(&self.{fname});").unwrap(),
            FieldType::VarInt => writeln!(out, "        writer.write_var_int(self.{fname});").unwrap(),
            FieldType::VarUInt => writeln!(out, "        writer.write_var_uint(self.{fname});").unwrap(),
            FieldType::VarShort => writeln!(out, "        writer.write_var_short(self.{fname});").unwrap(),
            FieldType::VarUShort => writeln!(out, "        writer.write_var_ushort(self.{fname});").unwrap(),
            FieldType::VarLong => writeln!(out, "        writer.write_var_long(self.{fname});").unwrap(),
            FieldType::VarULong => writeln!(out, "        writer.write_var_ulong(self.{fname});").unwrap(),
            FieldType::ByteArray => {
                writeln!(out, "        writer.write_var_int(self.{fname}.len() as i32);").unwrap();
                writeln!(out, "        writer.write_bytes(&self.{fname});").unwrap();
            }
            FieldType::Type(_) => {
                writeln!(out, "        self.{fname}.serialize(writer);").unwrap();
            }
            FieldType::Vector { inner, length_type } => {
                let len_write = length_write_method(length_type);
                writeln!(out, "        writer.{len_write}(self.{fname}.len() as _);").unwrap();
                match inner.as_ref() {
                    FieldType::TypeManager(tn) if tn.is_empty() => {
                        writeln!(out, "        // polymorphic vector (unresolved base type)").unwrap();
                    }
                    FieldType::TypeManager(_) => {
                        writeln!(out, "        for item in &self.{fname} {{").unwrap();
                        writeln!(out, "            writer.write_ushort(item.get_type_id());").unwrap();
                        writeln!(out, "            item.serialize(writer);").unwrap();
                        writeln!(out, "        }}").unwrap();
                    }
                    FieldType::Type(_) => {
                        writeln!(out, "        for item in &self.{fname} {{").unwrap();
                        writeln!(out, "            item.serialize(writer);").unwrap();
                        writeln!(out, "        }}").unwrap();
                    }
                    FieldType::String => {
                        writeln!(out, "        for item in &self.{fname} {{").unwrap();
                        writeln!(out, "            writer.write_utf(item);").unwrap();
                        writeln!(out, "        }}").unwrap();
                    }
                    _ => {
                        let elem_write = primitive_write_method(inner);
                        writeln!(out, "        for item in &self.{fname} {{").unwrap();
                        writeln!(out, "            writer.{elem_write}(*item);").unwrap();
                        writeln!(out, "        }}").unwrap();
                    }
                }
            }
            FieldType::TypeManager(name) => {
                if name.is_empty() {
                    writeln!(out, "        writer.write_bytes(&self.{fname});").unwrap();
                } else {
                    writeln!(out, "        writer.write_ushort(self.{fname}.get_type_id());").unwrap();
                    writeln!(out, "        (*self.{fname}).serialize(writer);").unwrap();
                }
            }
            FieldType::Long => writeln!(out, "        writer.write_var_long(self.{fname});").unwrap(),
            FieldType::ULong => writeln!(out, "        writer.write_var_ulong(self.{fname});").unwrap(),
        }
        i += 1;
    }
}

// ─── Deserialize body ────────────────────────────────────────────

fn write_deserialize_body(
    out: &mut String,
    fields: &[crate::extractor::ProtocolField],
    bool_groups: &HashMap<usize, Vec<usize>>,
) {
    // Pre-read boolean flags before the struct literal
    let mut bool_var_count = 0;
    for (&start, group) in bool_groups {
        writeln!(out, "        let _flag{bool_var_count} = reader.read_byte()?;").unwrap();
        let _ = (start, group);
        bool_var_count += 1;
    }

    // We need a different approach: deserialize sequentially, not in struct literal,
    // because bool groups need to be read first
    writeln!(out, "        Ok(Self {{").unwrap();

    let mut i = 0;
    let mut flag_idx = 0;
    while i < fields.len() {
        let field = &fields[i];
        let fname = sanitize_field_name(&field.name);

        if let Some(group) = bool_groups.get(&i) {
            // This is wrong — we need to read the flag byte BEFORE the struct literal
            // Let's use a different approach: read everything sequentially
            // For now, inline the flag reads
            for (bit, &fi) in group.iter().enumerate() {
                let gname = sanitize_field_name(&fields[fi].name);
                writeln!(out, "            {gname}: boolean_byte_wrapper::get_flag(_flag{flag_idx}, {bit})?,").unwrap();
            }
            flag_idx += 1;
            i += group.len();
            continue;
        }

        if field.write_method == "BooleanByteWrapper" {
            i += 1;
            continue;
        }

        match &field.field_type {
            FieldType::Bool => writeln!(out, "            {fname}: reader.read_boolean()?,").unwrap(),
            FieldType::Byte => writeln!(out, "            {fname}: reader.read_byte()?,").unwrap(),
            FieldType::UByte => writeln!(out, "            {fname}: reader.read_byte()?,").unwrap(),
            FieldType::Short => writeln!(out, "            {fname}: reader.read_short()?,").unwrap(),
            FieldType::UShort => writeln!(out, "            {fname}: reader.read_ushort()?,").unwrap(),
            FieldType::Int => writeln!(out, "            {fname}: reader.read_int()?,").unwrap(),
            FieldType::UInt => writeln!(out, "            {fname}: reader.read_uint()?,").unwrap(),
            FieldType::Float => writeln!(out, "            {fname}: reader.read_float()?,").unwrap(),
            FieldType::Double => writeln!(out, "            {fname}: reader.read_double()?,").unwrap(),
            FieldType::String => writeln!(out, "            {fname}: reader.read_utf()?,").unwrap(),
            FieldType::VarInt => writeln!(out, "            {fname}: reader.read_var_int()?,").unwrap(),
            FieldType::VarUInt => writeln!(out, "            {fname}: reader.read_var_uint()?,").unwrap(),
            FieldType::VarShort => writeln!(out, "            {fname}: reader.read_var_short()?,").unwrap(),
            FieldType::VarUShort => writeln!(out, "            {fname}: reader.read_var_ushort()?,").unwrap(),
            FieldType::VarLong => writeln!(out, "            {fname}: reader.read_var_long()?,").unwrap(),
            FieldType::VarULong => writeln!(out, "            {fname}: reader.read_var_ulong()?,").unwrap(),
            FieldType::ByteArray => {
                writeln!(out, "            {fname}: {{").unwrap();
                writeln!(out, "                let len = reader.read_var_int()? as usize;").unwrap();
                writeln!(out, "                reader.read_bytes(len)?").unwrap();
                writeln!(out, "            }},").unwrap();
            }
            FieldType::Type(type_name) => {
                if type_name.is_empty() {
                    writeln!(out, "            {fname}: DofusDeserialize::deserialize(reader)?,").unwrap();
                } else {
                    writeln!(out, "            {fname}: {type_name}::deserialize(reader)?,").unwrap();
                }
            }
            FieldType::Vector { inner, length_type } => {
                let len_read = length_read_method(length_type);
                writeln!(out, "            {fname}: {{").unwrap();
                writeln!(out, "                let count = reader.{len_read}()? as usize;").unwrap();
                writeln!(out, "                let mut v = Vec::with_capacity(count);").unwrap();
                writeln!(out, "                for _ in 0..count {{").unwrap();
                match inner.as_ref() {
                    FieldType::Type(tn) => {
                        if tn.is_empty() {
                            writeln!(out, "                    v.push(DofusDeserialize::deserialize(reader)?);").unwrap();
                        } else {
                            writeln!(out, "                    v.push({tn}::deserialize(reader)?);").unwrap();
                        }
                    }
                    FieldType::TypeManager(tn) if tn.is_empty() => {
                        writeln!(out, "                    v.push(Default::default());").unwrap();
                    }
                    FieldType::TypeManager(tn) => {
                        let variant_name = format!("{}Variant", tn);
                        writeln!(out, "                    let type_id = reader.read_ushort()?;").unwrap();
                        writeln!(out, "                    v.push({variant_name}::deserialize_with_id(type_id, reader)?);").unwrap();
                    }
                    _ => {
                        let elem_read = primitive_read_method(inner);
                        writeln!(out, "                    v.push(reader.{elem_read}()?);").unwrap();
                    }
                }
                writeln!(out, "                }}").unwrap();
                writeln!(out, "                v").unwrap();
                writeln!(out, "            }},").unwrap();
            }
            FieldType::TypeManager(type_name) => {
                if type_name.is_empty() {
                    writeln!(out, "            {fname}: Default::default(),").unwrap();
                } else {
                    let variant_name = format!("{}Variant", type_name);
                    writeln!(out, "            {fname}: {{").unwrap();
                    writeln!(out, "                let type_id = reader.read_ushort()?;").unwrap();
                    writeln!(out, "                Box::new({variant_name}::deserialize_with_id(type_id, reader)?)").unwrap();
                    writeln!(out, "            }},").unwrap();
                }
            }
            FieldType::Long => writeln!(out, "            {fname}: reader.read_var_long()?,").unwrap(),
            FieldType::ULong => writeln!(out, "            {fname}: reader.read_var_ulong()?,").unwrap(),
        }
        i += 1;
    }

    writeln!(out, "        }})").unwrap();
}

// ─── Registry ────────────────────────────────────────────────────

// ─── Enum generation ─────────────────────────────────────────────

fn generate_enums(enums: &[ProtocolEnum], dir: &Path) -> anyhow::Result<()> {
    let mut mod_rs = String::new();
    writeln!(mod_rs, "// Auto-generated by protocol-gen — do not edit\n")?;

    for e in enums {
        let file_name = to_snake_case(&e.name);
        let file_path = dir.join(format!("{file_name}.rs"));

        let rust_type = match e.value_type.as_str() {
            "int" => "i32",
            _ => "u32", // uint and default
        };

        let mut code = String::new();
        writeln!(code, "// Auto-generated by protocol-gen — do not edit")?;
        writeln!(code, "#![allow(dead_code)]\n")?;
        for (name, val) in &e.values {
            writeln!(code, "pub const {}: {} = {};", name, rust_type, val)?;
        }

        std::fs::write(&file_path, &code)?;
        writeln!(mod_rs, "pub mod {file_name};")?;
    }

    std::fs::write(dir.join("mod.rs"), &mod_rs)?;
    Ok(())
}

// ─── Polymorphic variant enum generation ─────────────────────────

fn generate_variant_enums(hierarchies: &[TypeHierarchy], types_dir: &Path) -> anyhow::Result<()> {
    // Append to types/mod.rs
    let mod_rs_path = types_dir.join("mod.rs");
    let mut mod_rs = std::fs::read_to_string(&mod_rs_path).unwrap_or_default();

    writeln!(mod_rs, "\n// Polymorphic variant enums")?;
    writeln!(mod_rs, "mod variants;")?;
    writeln!(mod_rs, "pub use variants::*;")?;

    std::fs::write(&mod_rs_path, &mod_rs)?;

    // Generate variants.rs with all variant enums
    let mut code = String::new();
    writeln!(code, "// Auto-generated by protocol-gen — do not edit")?;
    writeln!(code, "#![allow(unused_imports, dead_code)]\n")?;
    writeln!(code, "use dofus_io::{{BigEndianReader, BigEndianWriter, DofusDeserialize, DofusSerialize}};")?;
    writeln!(code, "use super::*;")?;
    writeln!(code, "use anyhow::Result;\n")?;

    for h in hierarchies {
        let enum_name = format!("{}Variant", h.base_name);

        // Enum definition
        writeln!(code, "/// Polymorphic enum for {} hierarchy", h.base_name)?;
        writeln!(code, "#[derive(Debug, Clone)]")?;
        writeln!(code, "pub enum {} {{", enum_name)?;
        for (variant_name, _) in &h.variants {
            writeln!(code, "    {}({}),", variant_name, variant_name)?;
        }
        writeln!(code, "}}\n")?;

        // Default impl
        if let Some((first, _)) = h.variants.first() {
            writeln!(code, "impl Default for {} {{", enum_name)?;
            writeln!(code, "    fn default() -> Self {{")?;
            writeln!(code, "        Self::{}({}::default())", first, first)?;
            writeln!(code, "    }}")?;
            writeln!(code, "}}\n")?;
        }

        // get_type_id
        writeln!(code, "impl {} {{", enum_name)?;
        writeln!(code, "    pub fn get_type_id(&self) -> u16 {{")?;
        writeln!(code, "        match self {{")?;
        for (variant_name, id) in &h.variants {
            writeln!(code, "            Self::{}(_) => {},", variant_name, id)?;
        }
        writeln!(code, "        }}")?;
        writeln!(code, "    }}\n")?;

        // deserialize_with_id
        writeln!(code, "    pub fn deserialize_with_id(type_id: u16, reader: &mut BigEndianReader) -> Result<Self> {{")?;
        writeln!(code, "        match type_id {{")?;
        for (variant_name, id) in &h.variants {
            writeln!(code, "            {} => Ok(Self::{}({}::deserialize(reader)?)),", id, variant_name, variant_name)?;
        }
        writeln!(code, "            _ => Err(anyhow::anyhow!(\"Unknown {} type_id: {{}}\", type_id)),", h.base_name)?;
        writeln!(code, "        }}")?;
        writeln!(code, "    }}")?;
        writeln!(code, "}}\n")?;

        // DofusSerialize
        writeln!(code, "impl DofusSerialize for {} {{", enum_name)?;
        writeln!(code, "    fn serialize(&self, writer: &mut BigEndianWriter) {{")?;
        writeln!(code, "        match self {{")?;
        for (variant_name, _) in &h.variants {
            writeln!(code, "            Self::{}(v) => v.serialize(writer),", variant_name)?;
        }
        writeln!(code, "        }}")?;
        writeln!(code, "    }}")?;
        writeln!(code, "}}\n")?;

        // DofusDeserialize (delegates to base type, user should use deserialize_with_id)
        writeln!(code, "impl DofusDeserialize for {} {{", enum_name)?;
        writeln!(code, "    fn deserialize(reader: &mut BigEndianReader) -> Result<Self> {{")?;
        if let Some((first, _)) = h.variants.first() {
            writeln!(code, "        Ok(Self::{}({}::deserialize(reader)?))", first, first)?;
        } else {
            writeln!(code, "        Err(anyhow::anyhow!(\"Cannot deserialize {} without type_id\"))", enum_name)?;
        }
        writeln!(code, "    }}")?;
        writeln!(code, "}}\n")?;
    }

    std::fs::write(types_dir.join("variants.rs"), &code)?;
    Ok(())
}

fn generate_registry(classes: &[ProtocolClass], output_dir: &Path) -> anyhow::Result<()> {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by protocol-gen — do not edit")?;
    writeln!(out, "#![allow(unused_imports, dead_code)]\n")?;
    writeln!(out, "use std::collections::HashMap;\n")?;

    writeln!(out, "pub fn message_names() -> HashMap<u16, &'static str> {{")?;
    writeln!(out, "    let mut m = HashMap::new();")?;
    for cls in classes {
        if cls.is_message {
            writeln!(out, "    m.insert({}, \"{}\");", cls.protocol_id, cls.name)?;
        }
    }
    writeln!(out, "    m")?;
    writeln!(out, "}}\n")?;

    writeln!(out, "pub fn type_names() -> HashMap<u16, &'static str> {{")?;
    writeln!(out, "    let mut m = HashMap::new();")?;
    for cls in classes {
        if !cls.is_message {
            writeln!(out, "    m.insert({}, \"{}\");", cls.protocol_id, cls.name)?;
        }
    }
    writeln!(out, "    m")?;
    writeln!(out, "}}")?;

    std::fs::write(output_dir.join("registry.rs"), &out)?;
    Ok(())
}

fn generate_mod_rs(
    output_dir: &Path,
    _groups: &HashMap<String, Vec<&ProtocolClass>>,
) -> anyhow::Result<()> {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by protocol-gen — do not edit\n")?;
    writeln!(out, "pub mod enums;")?;
    writeln!(out, "pub mod messages;")?;
    writeln!(out, "pub mod types;")?;
    writeln!(out, "pub mod registry;")?;
    std::fs::write(output_dir.join("mod.rs"), &out)?;
    Ok(())
}

// ─── Utilities ───────────────────────────────────────────────────

fn field_type_to_rust(ft: &FieldType) -> String {
    match ft {
        FieldType::Bool => "bool".into(),
        FieldType::Byte => "u8".into(),
        FieldType::UByte => "u8".into(),
        FieldType::Short => "i16".into(),
        FieldType::UShort => "u16".into(),
        FieldType::Int | FieldType::VarInt => "i32".into(),
        FieldType::UInt | FieldType::VarUInt => "u32".into(),
        FieldType::Long | FieldType::VarLong => "i64".into(),
        FieldType::ULong | FieldType::VarULong => "u64".into(),
        FieldType::Float => "f32".into(),
        FieldType::Double => "f64".into(),
        FieldType::String => "String".into(),
        FieldType::VarShort => "i16".into(),
        FieldType::VarUShort => "u16".into(),
        FieldType::ByteArray => "Vec<u8>".into(),
        FieldType::Type(name) => {
            if name.is_empty() { "Vec<u8>".into() }
            else {
                // Strip Vector.<> wrapper if present
                if let Some(inner) = name.strip_prefix("Vector.<").and_then(|s| s.strip_suffix('>')) {
                    format!("Vec<{inner}>")
                } else {
                    name.clone()
                }
            }
        }
        FieldType::Vector { inner, .. } => {
            let inner_type = field_type_to_rust(inner);
            format!("Vec<{inner_type}>")
        }
        FieldType::TypeManager(name) => {
            if name.is_empty() { "Vec<u8>".into() }
            else {
                let base = name.strip_prefix("Vector.<")
                    .and_then(|s| s.strip_suffix('>'))
                    .unwrap_or(name);
                format!("Box<{}Variant>", base)
            }
        }
    }
}

fn length_write_method(length_type: &str) -> &'static str {
    match length_type {
        "writeVarInt" => "write_var_int",
        "writeUnsignedShort" | "writeUShort" => "write_ushort",
        "writeByte" => "write_byte",
        _ => "write_short",
    }
}

fn length_read_method(length_type: &str) -> &'static str {
    match length_type {
        "writeVarInt" => "read_var_int",
        "writeUnsignedShort" | "writeUShort" => "read_ushort",
        "writeByte" => "read_byte",
        _ => "read_ushort",
    }
}

fn primitive_write_method(ft: &FieldType) -> &'static str {
    match ft {
        FieldType::Byte => "write_byte",
        FieldType::UByte => "write_byte",
        FieldType::Short => "write_short",
        FieldType::UShort => "write_ushort",
        FieldType::Int => "write_int",
        FieldType::UInt => "write_uint",
        FieldType::Float => "write_float",
        FieldType::Double => "write_double",
        FieldType::VarInt => "write_var_int",
        FieldType::VarUInt => "write_var_uint",
        FieldType::VarShort => "write_var_short",
        FieldType::VarUShort => "write_var_ushort",
        FieldType::VarLong => "write_var_long",
        FieldType::VarULong => "write_var_ulong",
        FieldType::Bool => "write_boolean",
        FieldType::String => "write_utf",
        _ => "write_byte",
    }
}

fn primitive_read_method(ft: &FieldType) -> &'static str {
    match ft {
        FieldType::Byte => "read_byte",
        FieldType::UByte => "read_byte",
        FieldType::Short => "read_short",
        FieldType::UShort => "read_ushort",
        FieldType::Int => "read_int",
        FieldType::UInt => "read_uint",
        FieldType::Float => "read_float",
        FieldType::Double => "read_double",
        FieldType::VarInt => "read_var_int",
        FieldType::VarUInt => "read_var_uint",
        FieldType::VarShort => "read_var_short",
        FieldType::VarUShort => "read_var_ushort",
        FieldType::VarLong => "read_var_long",
        FieldType::VarULong => "read_var_ulong",
        FieldType::Bool => "read_boolean",
        FieldType::String => "read_utf",
        _ => "read_byte",
    }
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(ch.to_lowercase().next().unwrap());
        } else {
            result.push(ch);
        }
    }
    result
}

fn sanitize_field_name(name: &str) -> String {
    let snake = to_snake_case(name);
    match snake.as_str() {
        "type" => "r#type".to_string(),
        "self" => "self_".to_string(),
        "super" => "super_".to_string(),
        "move" => "move_".to_string(),
        "ref" => "ref_".to_string(),
        "match" => "match_".to_string(),
        "mod" => "mod_".to_string(),
        "box" => "box_".to_string(),
        "yield" => "yield_".to_string(),
        "return" => "return_".to_string(),
        "where" => "where_".to_string(),
        _ => snake,
    }
}

/// Recursively collect all TypeManager base type names from a field type.
fn collect_type_manager_refs(ft: &FieldType, out: &mut HashSet<String>) {
    match ft {
        FieldType::TypeManager(name) if !name.is_empty() => {
            out.insert(name.clone());
        }
        FieldType::Vector { inner, .. } => {
            collect_type_manager_refs(inner, out);
        }
        _ => {}
    }
}
