//! A* pathfinding on the Dofus isometric grid.
//!
//! The Dofus map is a diamond (isometric) grid of 560 cells (14×20×2).
//! Each cell has up to 8 neighbors in cardinal + diagonal directions.
//!
//! Coordinate system (from CellIdConverter.as):
//!   cellId = (x - y) * MAP_WIDTH + y + (x - y) / 2
//!   Coordinates (x, y) are generated by the staggered row pattern.
//!
//! Directions (0-7): E, SE, S, SW, W, NW, N, NE
//! COORDINATES_DIRECTION offsets in (x, y):
//!   0 E:  (+1, +1)   1 SE: (+1,  0)   2 S:  (+1, -1)   3 SW: ( 0, -1)
//!   4 W:  (-1, -1)   5 NW: (-1,  0)   6 N:  (-1, +1)   7 NE: ( 0, +1)

use crate::dlm::{CellData, MapData, MAP_CELLS_COUNT, MAP_WIDTH};
use std::collections::BinaryHeap;
use std::cmp::Ordering;

/// Map grid coordinate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Coord {
    pub x: i32,
    pub y: i32,
}

/// Direction offsets (dx, dy) for 8 directions.
const DIR_OFFSETS: [(i32, i32); 8] = [
    (1, 1),   // 0 East
    (1, 0),   // 1 South-East
    (1, -1),  // 2 South
    (0, -1),  // 3 South-West
    (-1, -1), // 4 West
    (-1, 0),  // 5 North-West
    (-1, 1),  // 6 North
    (0, 1),   // 7 North-East
];

/// Precomputed cell ID → coordinate table.
/// Built once at first use, same algorithm as CellIdConverter.init().
fn build_cell_coords() -> Vec<Coord> {
    let mut coords = vec![Coord { x: 0, y: 0 }; MAP_CELLS_COUNT];
    let mut cell = 0usize;
    let mut start_x: i32 = 0;
    let mut start_y: i32 = 0;

    for _row in 0..20 {
        // First sub-row
        for b in 0..MAP_WIDTH as i32 {
            if cell < MAP_CELLS_COUNT {
                coords[cell] = Coord {
                    x: start_x + b,
                    y: start_y + b,
                };
                cell += 1;
            }
        }
        start_x += 1;
        // Second sub-row
        for b in 0..MAP_WIDTH as i32 {
            if cell < MAP_CELLS_COUNT {
                coords[cell] = Coord {
                    x: start_x + b,
                    y: start_y + b,
                };
                cell += 1;
            }
        }
        start_y -= 1;
    }

    coords
}

/// Convert (x, y) coordinates to cell ID.
/// Returns None if out of bounds.
fn coord_to_cell_id(x: i32, y: i32) -> Option<u16> {
    let diff = x - y;
    let id = diff * MAP_WIDTH as i32 + y + diff / 2;
    if id >= 0 && (id as usize) < MAP_CELLS_COUNT {
        Some(id as u16)
    } else {
        None
    }
}

/// Get the coordinate of a cell.
pub fn cell_coord(cell_id: u16) -> Coord {
    CELL_COORDS[cell_id as usize]
}

/// Get all valid neighbor cells (up to 8) for a given cell.
pub fn cell_neighbours(cell_id: u16) -> Vec<(u16, u8)> {
    let coord = CELL_COORDS[cell_id as usize];
    let mut result = Vec::with_capacity(8);

    for (dir, &(dx, dy)) in DIR_OFFSETS.iter().enumerate() {
        let nx = coord.x + dx;
        let ny = coord.y + dy;
        if let Some(nid) = coord_to_cell_id(nx, ny) {
            if nid != cell_id {
                result.push((nid, dir as u8));
            }
        }
    }

    result
}

/// Chebyshev distance (max of abs diffs) — admissible heuristic for 8-dir grid.
fn heuristic(a: u16, b: u16) -> u32 {
    let ca = CELL_COORDS[a as usize];
    let cb = CELL_COORDS[b as usize];
    let dx = (ca.x - cb.x).unsigned_abs();
    let dy = (ca.y - cb.y).unsigned_abs();
    dx.max(dy)
}

/// Manhattan distance in the Dofus coordinate system.
pub fn distance(a: u16, b: u16) -> u32 {
    let ca = CELL_COORDS[a as usize];
    let cb = CELL_COORDS[b as usize];
    let dx = (ca.x - cb.x).unsigned_abs();
    let dy = (ca.y - cb.y).unsigned_abs();
    dx + dy
}

/// Get the direction (0-7) from one cell to an adjacent cell.
pub fn direction_between(from: u16, to: u16) -> Option<u8> {
    let cf = CELL_COORDS[from as usize];
    let ct = CELL_COORDS[to as usize];
    let dx = (ct.x - cf.x).signum();
    let dy = (ct.y - cf.y).signum();

    DIR_OFFSETS
        .iter()
        .position(|&(ox, oy)| ox == dx && oy == dy)
        .map(|d| d as u8)
}

// ─── A* Pathfinding ────────────────────────────────────────────────

/// A* node for the priority queue.
#[derive(Clone, Eq, PartialEq)]
struct Node {
    cell_id: u16,
    f_score: u32, // g + h
}

impl Ord for Node {
    fn cmp(&self, other: &Self) -> Ordering {
        other.f_score.cmp(&self.f_score) // min-heap
    }
}

impl PartialOrd for Node {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

/// Find the shortest path between two cells on a map.
///
/// Returns the path as a list of cell IDs (including start and end),
/// or None if no path exists.
///
/// `max_cost` limits the search (e.g., movement points in combat).
pub fn find_path(
    map: &MapData,
    start: u16,
    end: u16,
    max_cost: Option<u32>,
) -> Option<Vec<u16>> {
    if start == end {
        return Some(vec![start]);
    }

    if (end as usize) >= map.cells.len() || !map.cells[end as usize].is_walkable() {
        return None;
    }

    let mut g_score = vec![u32::MAX; MAP_CELLS_COUNT];
    let mut came_from = vec![u16::MAX; MAP_CELLS_COUNT];
    let mut closed = vec![false; MAP_CELLS_COUNT];

    g_score[start as usize] = 0;

    let mut open = BinaryHeap::new();
    open.push(Node {
        cell_id: start,
        f_score: heuristic(start, end),
    });

    while let Some(Node { cell_id, .. }) = open.pop() {
        if cell_id == end {
            // Reconstruct path
            let mut path = Vec::new();
            let mut current = end;
            while current != start {
                path.push(current);
                current = came_from[current as usize];
            }
            path.push(start);
            path.reverse();
            return Some(path);
        }

        if closed[cell_id as usize] {
            continue;
        }
        closed[cell_id as usize] = true;

        let current_g = g_score[cell_id as usize];

        // Check max cost
        if let Some(max) = max_cost {
            if current_g >= max {
                continue;
            }
        }

        for (neighbour, dir) in cell_neighbours(cell_id) {
            if closed[neighbour as usize] {
                continue;
            }

            // Check walkability
            if !map.cells[neighbour as usize].is_walkable() {
                continue;
            }

            // For diagonal moves, check that adjacent cardinal cells are accessible
            // (prevents cutting through diagonal walls)
            if is_diagonal(dir) {
                let (adj1, adj2) = diagonal_adjacents(dir);
                let coord = CELL_COORDS[cell_id as usize];
                let (dx1, dy1) = DIR_OFFSETS[adj1 as usize];
                let (dx2, dy2) = DIR_OFFSETS[adj2 as usize];

                let adj1_ok = coord_to_cell_id(coord.x + dx1, coord.y + dy1)
                    .map(|c| map.cells[c as usize].is_walkable())
                    .unwrap_or(false);
                let adj2_ok = coord_to_cell_id(coord.x + dx2, coord.y + dy2)
                    .map(|c| map.cells[c as usize].is_walkable())
                    .unwrap_or(false);

                if !adj1_ok && !adj2_ok {
                    continue; // Can't cut through diagonal wall
                }
            }

            // Cost: 1 for all moves (diagonal moves are equivalent in Dofus grid)
            let tentative_g = current_g + 1;

            if tentative_g < g_score[neighbour as usize] {
                g_score[neighbour as usize] = tentative_g;
                came_from[neighbour as usize] = cell_id;
                open.push(Node {
                    cell_id: neighbour,
                    f_score: tentative_g + heuristic(neighbour, end),
                });
            }
        }
    }

    None // No path found
}

/// Check if a direction is diagonal (odd directions: SE, SW, NW, NE).
fn is_diagonal(dir: u8) -> bool {
    dir % 2 == 1
}

/// For a diagonal direction, return the two adjacent cardinal directions.
fn diagonal_adjacents(dir: u8) -> (u8, u8) {
    // dir is odd (1,3,5,7). Adjacent cardinals are dir-1 and dir+1 (mod 8).
    ((dir + 7) % 8, (dir + 1) % 8)
}

// ─── Line of Sight ─────────────────────────────────────────────────

/// Check if there is a clear line of sight between two cells.
/// Uses the `los` flag from cell data.
pub fn has_line_of_sight(map: &MapData, from: u16, to: u16) -> bool {
    let c0 = CELL_COORDS[from as usize];
    let c1 = CELL_COORDS[to as usize];

    // Bresenham's line algorithm on the coordinate grid
    let dx = (c1.x - c0.x).abs();
    let dy = (c1.y - c0.y).abs();
    let sx = if c0.x < c1.x { 1 } else { -1 };
    let sy = if c0.y < c1.y { 1 } else { -1 };
    let mut err = dx - dy;

    let mut x = c0.x;
    let mut y = c0.y;

    loop {
        if x == c1.x && y == c1.y {
            return true;
        }

        if let Some(cell_id) = coord_to_cell_id(x, y) {
            if cell_id != from && cell_id != to {
                if !map.cells[cell_id as usize].los {
                    return false; // Blocked
                }
            }
        } else {
            return false; // Out of bounds
        }

        let e2 = 2 * err;
        if e2 > -dy {
            err -= dy;
            x += sx;
        }
        if e2 < dx {
            err += dx;
            y += sy;
        }
    }
}

/// Validate a path sent by the client.
/// Checks that each step follows a valid neighbor and is walkable.
pub fn validate_path(map: &MapData, path: &[u16]) -> bool {
    if path.is_empty() {
        return true;
    }

    for window in path.windows(2) {
        let from = window[0];
        let to = window[1];

        // Check destination is walkable
        if (to as usize) >= map.cells.len() || !map.cells[to as usize].is_walkable() {
            return false;
        }

        // Check they are neighbors
        if !cell_neighbours(from).iter().any(|&(n, _)| n == to) {
            return false;
        }
    }

    true
}

// ─── Static initialization ─────────────────────────────────────────

use std::sync::LazyLock;

static CELL_COORDS: LazyLock<Vec<Coord>> = LazyLock::new(build_cell_coords);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dlm;

    #[test]
    fn cell_coords_count() {
        assert_eq!(CELL_COORDS.len(), MAP_CELLS_COUNT);
    }

    #[test]
    fn coord_roundtrip() {
        // Every cell should roundtrip through coord conversion
        for id in 0..MAP_CELLS_COUNT as u16 {
            let c = CELL_COORDS[id as usize];
            let back = coord_to_cell_id(c.x, c.y);
            assert_eq!(back, Some(id), "roundtrip failed for cell {id}: coord ({}, {})", c.x, c.y);
        }
    }

    #[test]
    fn cell_0_is_origin() {
        let c = CELL_COORDS[0];
        assert_eq!(c, Coord { x: 0, y: 0 });
    }

    #[test]
    fn cell_neighbours_count() {
        // Corner cells have fewer neighbors
        let n0 = cell_neighbours(0);
        assert!(n0.len() >= 2 && n0.len() <= 4, "cell 0 neighbours: {}", n0.len());

        // Middle cells should have up to 8
        let n280 = cell_neighbours(280);
        assert!(n280.len() >= 6, "cell 280 neighbours: {}", n280.len());
    }

    #[test]
    fn direction_between_adjacent() {
        // Cell 0 → Cell 1 should be some direction
        let dir = direction_between(0, 1);
        assert!(dir.is_some(), "cells 0→1 should be adjacent");
    }

    #[test]
    fn distance_to_self_is_zero() {
        assert_eq!(distance(100, 100), 0);
    }

    #[test]
    fn distance_is_symmetric() {
        assert_eq!(distance(0, 100), distance(100, 0));
        assert_eq!(distance(50, 500), distance(500, 50));
    }

    #[test]
    fn pathfind_on_open_map() {
        // Create a map where all cells are walkable
        let mut cells = vec![CellData::default(); MAP_CELLS_COUNT];
        for c in &mut cells {
            c.mov = true;
            c.los = true;
        }
        let map = dlm::MapData {
            version: 11,
            id: 1,
            sub_area_id: 1,
            top_neighbour_id: 0,
            bottom_neighbour_id: 0,
            left_neighbour_id: 0,
            right_neighbour_id: 0,
            cells,
        };

        // Path from cell 0 to cell 100
        let path = find_path(&map, 0, 100, None);
        assert!(path.is_some(), "should find path on open map");

        let path = path.unwrap();
        assert_eq!(*path.first().unwrap(), 0);
        assert_eq!(*path.last().unwrap(), 100);
        assert!(path.len() > 1);

        // Path should be valid
        assert!(validate_path(&map, &path));
    }

    #[test]
    fn pathfind_with_wall() {
        let mut cells = vec![CellData::default(); MAP_CELLS_COUNT];
        for c in &mut cells {
            c.mov = true;
            c.los = true;
        }

        // Block a row of cells to force a detour
        for i in 14..27 {
            cells[i].mov = false;
        }

        let map = dlm::MapData {
            version: 11,
            id: 1,
            sub_area_id: 1,
            top_neighbour_id: 0,
            bottom_neighbour_id: 0,
            left_neighbour_id: 0,
            right_neighbour_id: 0,
            cells,
        };

        // Cell 0 (top) to cell 28 (just past the wall)
        let path = find_path(&map, 0, 28, None);
        assert!(path.is_some(), "should find path around wall");
        assert!(validate_path(&map, &path.as_ref().unwrap()));

        // Path should not go through blocked cells
        let path = path.unwrap();
        for &cell in &path {
            assert!(cell < 14 || cell >= 27 || cell == 28, "path goes through wall at cell {cell}");
        }
    }

    #[test]
    fn pathfind_no_path() {
        let mut cells = vec![CellData::default(); MAP_CELLS_COUNT];
        for c in &mut cells {
            c.mov = true;
        }

        // Completely surround cell 300 with walls
        for (nid, _) in cell_neighbours(300) {
            cells[nid as usize].mov = false;
        }

        let map = dlm::MapData {
            version: 11,
            id: 1,
            sub_area_id: 1,
            top_neighbour_id: 0,
            bottom_neighbour_id: 0,
            left_neighbour_id: 0,
            right_neighbour_id: 0,
            cells,
        };

        let path = find_path(&map, 0, 300, None);
        assert!(path.is_none(), "should not find path to surrounded cell");
    }

    #[test]
    fn pathfind_max_cost() {
        let mut cells = vec![CellData::default(); MAP_CELLS_COUNT];
        for c in &mut cells {
            c.mov = true;
        }
        let map = dlm::MapData {
            version: 11,
            id: 1,
            sub_area_id: 1,
            top_neighbour_id: 0,
            bottom_neighbour_id: 0,
            left_neighbour_id: 0,
            right_neighbour_id: 0,
            cells,
        };

        // With max_cost=3, can only reach cells within 3 steps
        let path = find_path(&map, 0, 100, Some(3));
        assert!(path.is_none(), "cell 100 should be unreachable in 3 steps from 0");

        // Nearby cell should be reachable
        let close = cell_neighbours(0)[0].0;
        let path = find_path(&map, 0, close, Some(3));
        assert!(path.is_some());
    }

    #[test]
    fn line_of_sight_open() {
        let mut cells = vec![CellData::default(); MAP_CELLS_COUNT];
        for c in &mut cells {
            c.mov = true;
            c.los = true;
        }
        let map = dlm::MapData {
            version: 11,
            id: 1,
            sub_area_id: 1,
            top_neighbour_id: 0,
            bottom_neighbour_id: 0,
            left_neighbour_id: 0,
            right_neighbour_id: 0,
            cells,
        };

        assert!(has_line_of_sight(&map, 0, 100));
        assert!(has_line_of_sight(&map, 100, 0));
    }

    #[test]
    fn line_of_sight_blocked() {
        let mut cells = vec![CellData::default(); MAP_CELLS_COUNT];
        for c in &mut cells {
            c.mov = true;
            c.los = true;
        }

        // Find a cell on the direct path from 0 to 100 and block it
        // First, find what cells the Bresenham line passes through
        let c0 = CELL_COORDS[0];
        let c1 = CELL_COORDS[100];
        // Pick a midpoint coordinate and block that cell
        let mid_x = (c0.x + c1.x) / 2;
        let mid_y = (c0.y + c1.y) / 2;
        if let Some(mid_cell) = coord_to_cell_id(mid_x, mid_y) {
            cells[mid_cell as usize].los = false;
            // Also block adjacent cells to ensure the line is truly blocked
            for (n, _) in cell_neighbours(mid_cell) {
                cells[n as usize].los = false;
            }
        }

        let map = dlm::MapData {
            version: 11,
            id: 1,
            sub_area_id: 1,
            top_neighbour_id: 0,
            bottom_neighbour_id: 0,
            left_neighbour_id: 0,
            right_neighbour_id: 0,
            cells,
        };

        assert!(!has_line_of_sight(&map, 0, 100));
    }

    #[test]
    fn validate_path_rejects_teleport() {
        let mut cells = vec![CellData::default(); MAP_CELLS_COUNT];
        for c in &mut cells {
            c.mov = true;
        }
        let map = dlm::MapData {
            version: 11,
            id: 1,
            sub_area_id: 1,
            top_neighbour_id: 0,
            bottom_neighbour_id: 0,
            left_neighbour_id: 0,
            right_neighbour_id: 0,
            cells,
        };

        // Non-adjacent cells = invalid path (teleport)
        assert!(!validate_path(&map, &[0, 100]));
    }
}
